/**
 *  The MIT License (MIT)
 *
 *  Copyright (c) 2015 Kyle Hollins Wray, University of Massachusetts
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of
 *  this software and associated documentation files (the "Software"), to deal in
 *  the Software without restriction, including without limitation the rights to
 *  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 *  the Software, and to permit persons to whom the Software is furnished to do so,
 *  subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 *  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 *  COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 *  IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 *  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */


#ifndef EPIC_NAVIGATION_NODE_H
#define EPIC_NAVIGATION_NODE_H


#include <ros/ros.h>

#include <nav_msgs/OccupancyGrid.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseWithCovarianceStamped.h>

#include <harmonic/harmonic.h>

// Generated by having the .srv files defined.
#include <epic/ModifyGoals.h>
#include <epic/SetCells.h>
#include <epic/ComputePath.h>

namespace epic {

#define EPIC_ALGORITHM_HARMONIC         0
#define EPIC_ALGORITHM_RRT_CONNECT      1
#define EPIC_ALGORITHM_RRT_STAR         2
#define EPIC_ALGORITHM_LAZY_RRT         3
#define EPIC_ALGORITHM_LAZY_PRM         4
#define EPIC_ALGORITHM_PRM_STAR         5
#define EPIC_ALGORITHM_LAZY_PRM_STAR    6
#define NUM_EPIC_ALGORITHMS             7

#define EPIC_OCCUPANCY_GRID_MAX                 100
#define EPIC_OCCUPANCY_GRID_OBSTACLE_THRESHOLD  50
#define EPIC_OCCUPANCY_GRID_MIN                 0
#define EPIC_OCCUPANCY_GRID_UNKNOWN             -1
#define EPIC_OCCUPANCY_GRID_NO_CHANGE           -2

class EpicNavigationNode {
public:
    /**
     *  The default constructor for the EpicNavigationNode. Defaults to 'harmonic'.
     *  TODO: update params
     */
    EpicNavigationNode(ros::NodeHandle &nh);

    /**
     *  The constructor for the EpicNavigationNode, enabling the selection of the planner.
     *  TODO: update params
     *  @param  alg     The algorithm to use (see defines above).
     */
    EpicNavigationNode(ros::NodeHandle &nh, unsigned int alg);

    /**
     *  The deconstructor for the EpicNavigationNode.
     */
    virtual ~EpicNavigationNode();

    /**
     *  Initialize the services and messages.
     *  @return True if successful in registering and subscribing, false otherwise.
     */
    bool initMsgs();

    /**
     *  Update the harmonic function or other planner one step.
     *  @param  num_steps   The number of steps to do for the algorithm.
     */
    void update(unsigned int num_steps);

private:
    /**
     *  Initialize the algorithm.
     *  @param  w   The new width.
     *  @param  h   The new height.
     */
    void initAlg(unsigned int w, unsigned int h);

    /**
     *  Uninitialize the algorithm.
     */
    void uninitAlg();

    /**
     *  Set the boundaries as obstacles for the occupancy grid (for whatever representation).
     */
    void setBoundariesAsObstacles();

    /**
     *  Convert a "float pixel" map coordinate to a world coordinate.
     *  @param  mx  The "float pixel" map x coordinate.
     *  @param  my  The "float pixel" map y coordinate.
     *  @param  wx  The world x coordinate. This will be modified.
     *  @param  wy  The world y coordinate. This will be modified.
     */
    void mapToWorld(float mx, float my, float &wx, float &wy) const;

    /**
     *  Convert a "float pixel" map coordinate to a world coordinate.
     *  @param  wx  The world x coordinate.
     *  @param  wy  The world y coordinate.
     *  @param  mx  The "float pixel" map x coordinate. This will be modified.
     *  @param  my  The "float pixel" map y coordinate. This will be modified.
     */
    bool worldToMap(float wx, float wy, float &mx, float &my) const;

    /**
     *  Check if a cell is a goal or not.
     *  @param  x   The x cell index.
     *  @param  y   The y cell index.
     *  @return True if it is a goal, false otherwise.
     */
    bool isCellGoal(unsigned int x, unsigned int y);

    /**
     *  Handler for receiving OccupancyGrid messages (see defines above; values differ here).
     *  @param  msg     The OccupancyGrid message.
     */
    void subOccupancyGrid(const nav_msgs::OccupancyGrid::ConstPtr &msg);

    // TODO: comment missing
	void subMapGoal(const geometry_msgs::PoseStamped::ConstPtr &msg);

    // TODO: comment missing
	void subMapPoseEstimate(const geometry_msgs::PoseWithCovarianceStamped::ConstPtr &msg);

    /**
     *  Handler for receiving add goal(s) service request. Assumption: These are not initially obstacles.
     *  @param  req     The AddGoal service request containing the goal location(s) to add.
     *  @param  res     The AddGoal service response containing if it was successful or not. 
     *  @return Returns true if successful, false otherwise.
     */
    bool srvAddGoals(epic::ModifyGoals::Request &req, epic::ModifyGoals::Response &res);

    /**
     *  Handler for receiving remove goal(s) messages. Assumption: Removed goals become free space.
     *  @param  req     The RemoveGoal service request containing the goal location(s) to remove.
     *  @param  res     The RemoveGoal service response containing if it was successful or not.
     *  @return Returns true if successful, false otherwise.
     */
    bool srvRemoveGoals(epic::ModifyGoals::Request &req, epic::ModifyGoals::Response &res);

    /**
     *  Handler for receiving set cells messages. This allows for quick updates to the occupancy grid.
     *  @param  req     The RemoveGoal service request containing the cells to set and resulting desired type.
     *  @param  res     The RemoveGoal service response containing if it was successful or not.
     *  @return Returns true if successful, false otherwise.
     */
    bool srvSetCells(epic::SetCells::Request &req, epic::SetCells::Response &res);

    /**
     *  Handler for service requests for generating Path messages.
     *  @param  req     The ComputePath service request containing the start location, max length, precision, etc.
     *  @param  res     The ComputePath service response containing the resulting path.
     *  @return Returns true if successful, false otherwise.
     */
    bool srvComputePath(epic::ComputePath::Request &req, epic::ComputePath::Response &res);

    // TODO: comment missing
    ros::NodeHandle private_node_handle;

    // The subscriber for the OccupancyGrid message.
    ros::Subscriber sub_occupancy_grid;

    // TODO: comment missing
    ros::Subscriber sub_map_goal;

    // TODO: comment missing
    ros::Subscriber sub_map_pose_estimate;

    // TODO: comment missing
    ros::Publisher pub_path;

    // TODO: comment missing
	bool goal_added;

    // The service for AddGoal.
    ros::ServiceServer srv_add_goals;

    // The service for RemoveGoal.
    ros::ServiceServer srv_remove_goals;

    // The service for SetCells.
    ros::ServiceServer srv_set_cells;

    // The service for ComputePath.
    ros::ServiceServer srv_compute_path;

    // Current width of the map.
    unsigned int width;

    // Current height of the map.
    unsigned int height;

    // Current resolution of the map.
    float resolution;

    // Current x origin offset of the map.
    float x_origin;

    // Current y origin offset of the map.
    float y_origin;

    // The algorithm to use. Default is EPIC_ALGORITHM_HARMONIC.
    unsigned int algorithm;

    // The Harmonic object for use if algorithm is EPIC_ALGORITHM_HARMONIC.
    Harmonic harmonic;

    // If this is GPU-capable, or not.
    bool gpu;

    // If this class' services and subscriptions have been properly initialized or not.
    bool init_msgs;

    // If this class' algorithm variables have been properly initialized or not.
    bool init_alg;

    // TODO: comment missing
    geometry_msgs::PoseStamped last_goal;

    // TODO: comment missing
    geometry_msgs::PoseStamped current_pose;

};

};


#endif // EPIC_NAVIGATION_NODE_H

